# Generated by Django 5.1.7 on 2025-04-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogbattle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserQuizAttempt',
        ),
    ]
